In [ ]:
SINCHANA AB AMB2248

In [2]:
s="hello"
print(s[:-5])

In [4]:
# python program for basic arithmetic operations
#using 1 d array
import numpy as np
arr=np.array([1,3,5,7,9])
sum=arr[0]+arr[2]
print("sum of two numbers ",sum)
diff=arr[3]-arr[2]
print("difference between two numbers",diff)
product=arr[1]*arr[3]
div=arr[4]/arr[1]
print("product of two numbers",product)
print("division of two numbers",div)

sum of two numbers  6
difference between two numbers 2
product of two numbers 21
division of two numbers 3.0


In [7]:
#slicing 1D array
import numpy as np
arr=np.array([2,4,6,8,12,14,16])
print(arr[3:6])
print(arr[:5])
print(arr[2:])
print(arr[-5:-1])
print(arr[:-1])




[ 8 12 14]
[ 2  4  6  8 12]
[ 6  8 12 14 16]
[ 6  8 12 14]
[ 2  4  6  8 12 14]


In [9]:
#slicing 2 D array
# from second element ,slice elements
#from index 1 to 4
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[1,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [13]:
# from both elements return index 2:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [ ]:
# from both elements ,slice index
#1 to index 4



In [18]:
# reshaping 
# convert the following 1 d array with 12 elements into 3D array
# the outermost dimension will have 2 arrays
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_array=arr.reshape(2,3,2)
print(new_array)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [19]:
# from both elements slice index
# 1 to index 4
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])


[[2 3 4]
 [7 8 9]]


In [21]:
# copy method
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [24]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr1=arr
arr[0]=45
print(arr)
print(arr1)

[45  2  3  4  5]
[45  2  3  4  5]


In [26]:
# resizing
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
arr.shape=(3,2)
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [27]:
import numpy as np
np.arange(1,14,4)

array([ 1,  5,  9, 13])

In [30]:
#write a progrmme to calculate the sum of 3rd and 4th element from the array
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [31]:
# create a 2 dimensional array 2*5 access the second element
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element of 1st dimension",arr[0,1])

2nd element of 1st dimension 2


In [36]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [3]:
#elements wise arithmetic operations
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [5]:
# concatenation along the rows and columns
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
concatenate_arr=np.concatenate((arr1,arr2),axis=0)# concatenate along thre rows
print(concatenate_arr)
concatenate_arr=np.concatenate((arr1,arr2),axis=1)# concatenate along the columns
print(concatenate_arr)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [12]:
#transpose
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
transposed_arr=arr.transpose()
print(transposed_arr)
print()

[[1 4]
 [2 5]
 [3 6]]



In [22]:
#flatenned 
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
flattened_arr=arr.flatten()
print(flattened_arr)

[1 2 3 4 5 6]


In [26]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("original arr.shape",arr.shape)
print(arr)
transposed_arr=arr.transpose()
print(transposed_arr)
print("transposed_arr.shape", transposed_arr.shape)




original arr.shape (2, 3)
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
transposed_arr.shape (3, 2)


In [28]:
# checking for complex numbers
import numpy as np
arr=np.array([1+1j,1+0j,4.5,3.2,2])
print("original array")
print(arr)

original array
[1. +1.j 1. +0.j 4.5+0.j 3.2+0.j 2. +0.j]


In [30]:
import numpy as np
arr=np.array([1+1j,1+0j,4.5,3.2,2])
print("checking for complex number")
print(np.iscomplex(arr))


checking for complex number
[ True False False False False]


In [32]:
print("checking for real number")
print(np.isreal(arr))

checking for real number
[False  True  True  True  True]


In [33]:
print("checking for scalar type:")
print(np.isscalar(3.1))

checking for scalar type:
True


In [34]:
print("checking for scalar type")
print(np.isscalar([3.1]))

checking for scalar type
False


In [35]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [37]:
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
one=np.ones((2,4))
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
empty1=np.empty((2,3))
empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
# 0D array
import numpy as np
arr=np.array([(2)])
print(arr)
print(arr.size)

[2]
1


In [47]:
print(arr.shape)

(1,)


In [48]:
print(type(arr))

<class 'numpy.ndarray'>


In [51]:
ndim=arr.ndim
print("number of dimension:",ndim)

number of dimension: 1


In [52]:
#single dimension array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
5
(5,)
<class 'numpy.ndarray'>
1


In [54]:
# 2 D array
import numpy as np
arr=np.array([[1,2,8],[3,4,9],[5,6,7]])
print(arr)

[[1 2 8]
 [3 4 9]
 [5 6 7]]


In [55]:
print(arr.size)
print(arr.shape)
print(type(arr))


9
(3, 3)
<class 'numpy.ndarray'>


In [57]:
arr=np.array([[2.0,1],[1,2]])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
print(arr.ndim)


[[2. 1.]
 [1. 2.]]
4
(2, 2)
<class 'numpy.ndarray'>
2


In [64]:
# create an array with 5 dimension and verify that it has 5 dimension
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print("number of dimension:",arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimension: 5


In [65]:
#array indexing
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1
