In [ ]:
SINCHANA AB AMB248

In [3]:
import numpy as np
crop_yield=np.array([
    [12.5,13.2,14.1,13.8,15.2],
    [10.3,11.5,10.8,12.1,11.9],
    [15.1,14.8,16.2,15.5,16.8],
    [11.2,10.9,12.3,11.7,12.8],
])
print("crop fields array (tons):")
print(crop_yield)
print(f"\nshape:{crop_yield.shape}")
print(f"data type:{crop_yield.dtype}")
print(f"total element:{crop_yield.size}")
print(f"number of dimension:{crop_yield.ndim}")


crop fields array (tons):
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

shape:(4, 5)
data type:float64
total element:20
number of dimension:2


In [11]:
# agriculture field operations
import numpy as np
total_yield=np.sum(crop_yield)
avg_yield_per_farm=np.mean(crop_yield,axis=1)
avg_yield_per_season=np.mean(crop_yield,axis=0)
max_yield=np.max(crop_yield)
min_yield=np.min(crop_yield)
print(f"\ntotal production:{total_yield}tons")
print(f"average  yield per farm:{avg_yield_per_farm}tons")
print(f" average yield  per season:{avg_yield_per_season}tons")
print(f"maximum yield:{max_yield}tons")
print(f"minimmmum yield:{min_yield}tons")



total production:262.7tons
average  yield per farm:[13.76 11.32 15.68 11.78]tons
 average yield  per season:[12.275 12.6   13.35  13.275 14.175]tons
maximum yield:16.8tons
minimmmum yield:10.3tons


In [24]:
# find best performing farm
import numpy as np
best_farm=np.argmax(avg_yield_per_farm)
print("\n best performing farm",best_farm+1)
print("their average yield",round(avg_yield_per_farm[best_farm],2),"tons")
#or
print("\n best performing farm:farm",{best_farm},2,"tons")




 best performing farm 3
their average yield 15.68 tons

 best performing farm:farm {2} 2 tons


In [31]:
# bolean indexing
exceptional=crop_yield>16
print(exceptional)
print("\n exceptional yield>(16):")
print(crop_yield[exceptional])
      


[[False False False False False]
 [False False False False False]
 [False False  True False  True]
 [False False False False False]]

 exceptional yield>(16):
[16.2 16.8]


In [35]:
# conditional operations
categories=np.where(crop_yield>16,"high"),
                    np.where(crop_yield>14,"medium","low")
print("\n yield categories")

print(categories)

IndentationError: unexpected indent (1877528975.py, line 3)